name: Build ZoLearn documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_REGION: "eu-north-1"
  SOURCE_DIR: "dist"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Generate HTML from README files
        run: node build-site.js

      - name: Deploying to Cloudfront
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
